"""add field to record creation date time stamp

Revision ID: cc9e4aa9512d
Revises: 
Create Date: 2024-10-16 12:35:27.115304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc9e4aa9512d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absence', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
